// permix/src/react/hooks.ts
import * as React from "react";

import type { Definition, Permix, Rules } from "../core";
import { createCheck } from "../core";

export interface PermixContext<T extends Definition> {
  permix: Permix<T>;
  isReady: boolean;
  rules: Rules<T> | null;
}

export const Context = React.createContext<PermixContext<any>>(null!);

export function usePermixContext() {
  const context = React.useContext(Context);

  if (!context) {
    throw new Error(
      "[Permix]: Looks like you forgot to wrap your app with <PermixProvider>"
    );
  }

  return context;
}

/**
 * Access Permix check and readiness state inside a React component.
 *
 * @link https://permix.letstri.dev/docs/integrations/react
 */
export function usePermix<T extends Definition>(
  permix: Pick<Permix<T>, "getRules" | "check">
) {
  const { isReady, rules } = usePermixContext();

  const check: Permix<T>["check"] = React.useCallback(
    (...args) =>
      createCheck<T>(() => (rules ?? permix.getRules()) as Rules<T> | null)(
        ...args
      ),
    [rules, permix]
  );

  return { check, isReady };
}

// permix/src/solid/hooks.ts
import { createContext, useContext } from "solid-js";

import type { Definition, Permix, Rules } from "../core";
import { createCheck } from "../core";

export interface PermixContext<T extends Definition> {
  permix: Permix<T>;
  isReady: boolean;
  rules: Rules<T> | null;
}

export const Context = createContext<PermixContext<any>>(null!);

export function usePermixContext() {
  const context = useContext(Context);

  if (!context) {
    throw new Error(
      "[Permix]: Looks like you forgot to wrap your app with <PermixProvider>"
    );
  }

  return context;
}

/**
 * Access Permix check and readiness state inside a Solid component.
 *
 * @link https://permix.letstri.dev/docs/integrations/solid
 */
export function usePermix<T extends Definition>(
  permix: Pick<Permix<T>, "getRules" | "check">
) {
  const context = usePermixContext();

  const check: Permix<T>["check"] = (...args) =>
    createCheck<T>(
      () => (context.rules ?? permix.getRules()) as Rules<T> | null
    )(...args);

  return { check, isReady: () => context.isReady };
}
